
import { Metadata } from "next";
// import GalleryPage from "./gallery/page";
export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};
export default function Home() {
  // throw new Error();
  return (
    <div>
      <h1>Hello World</h1>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Praesentium iusto corrupti nihil, quo voluptatem rerum accusamus tempora animi vitae deleniti ipsum, eius aperiam aliquam quae labore unde asperiores nobis. Numquam minus excepturi libero hic aperiam quos, incidunt ea sed dignissimos quia accusamus ex error impedit in fugit maiores, optio, suscipit doloribus dolore expedita animi repellendus rem consequuntur? Nam ratione deserunt aspernatur ipsam perspiciatis illo repellendus, quasi quia veritatis nulla, placeat sapiente laboriosam consectetur eaque non asperiores deleniti assumenda nisi reprehenderit quis ducimus explicabo aperiam dicta? Voluptatem aliquid, tenetur commodi aliquam cumque ad libero atque unde deleniti numquam eveniet, impedit aut. Vel, et? Quidem minima, ullam delectus voluptatum fugit, soluta beatae mollitia doloremque, sint libero ad officia. Exercitationem explicabo vel recusandae dolorem molestias nihil neque quasi maiores voluptatibus voluptas alias labore non voluptate magnam saepe quo, quia nulla sunt eaque tempora voluptatem nobis quaerat. Rerum libero rem alias sint dignissimos est, accusantium aspernatur at. Earum odio animi fugiat quia quae dolor eveniet perferendis, doloremque, consequuntur quidem voluptas dicta quibusdam ipsam modi alias officiis, expedita ad? Laborum ut voluptas accusamus nisi. Voluptas omnis non adipisci facilis minima commodi consequuntur, temporibus unde voluptatum veniam sint quam dolorum et, tempora debitis! Dolorem, amet unde?</p>
      {/* <GalleryPage/> */}
    </div>
  );
}
